##ARCHIVO AUN SIN REFACTORIZAR####  
""" import streamlit as st
import pymongo

class DataAccess:
   def __init__(self): 
      db_nameusr = st.secrets["database"]["dbname"]#.get("database",{}).get("dbname",{}) #["database"]["dbname"]
      collection_nameusr =  st.secrets["database"]["coll_usrs"]#.get("database", {}).get("coll_usrs","NotFound") #st.secrets["database"]["coll_usrs"]    
      db_namefilm =  st.secrets.get("dbfilmkommin",{}).get("dbname","NotFound") #st.secrets["dbfilmkommin"]["dbname"]
      collection_namefilm =  st.secrets.get("dbfilmkommin",{}).get("coll_usrs","NotFound")  #st.secrets["dbfilmkommin"]["coll_usrs"]
    
   def userinfo(self):
    db_name = self.db_nameusr
    collection_name = self.collection_nameusr
    return  db_name, collection_name

   def filmkom(self):
    db_name = self.db_namefilm
    collection_name =  self.collection_namefilm
    return db_name, collection_name

dbconn = DataAccess()
dbname, collection_name = dbconn.userinfo() 
print(f"Valores devueltos por firstext: {dbname}, {collection_name}")

 """


"""
 class DataAccess:
   def __init__(self): 
      db_nameusr = st.secrets.get("database",{}).get("dbname",{}) #["database"]["dbname"]
      collection_nameusr =  st.secrets.get("database", {}).get("coll_usrs","NotFound") #st.secrets["database"]["coll_usrs"]    
      db_namefilm =  st.secrets.get("dbfilmkommin",{}).get("dbname","NotFound") #st.secrets["dbfilmkommin"]["dbname"]
      collection_namefilm =  st.secrets.get("dbfilmkommin",{}).get("coll_usrs","NotFound")  #st.secrets["dbfilmkommin"]["coll_usrs"]
    
   def userinfo(self):
    db_name = self.db_nameusr
    collection_name = self.collection_nameusr
    return  db_name, collection_name

   def filmkom(self):
    db_name = self.db_namefilm
    collection_name =  self.collection_namefilm
    return db_name, collection_name 
"""